/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ifce;

import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author walmi
 */
public class chat extends javax.swing.JFrame {

    tela tela = new tela();
    String usuarioConectade;
    String ambNome;
    DefaultListModel<String> model = new DefaultListModel<String>();
    private Object mensagemText;

    private void initAssets() {
        String[] elementos = tela.exibirListaNaTela();
        for (String elemento : elementos) {
            model.addElement(elemento);
        }
        usuariosList.setModel(model);
        
        
    }

    public void setUsuarioConectade(String usuarioConectade) {
        this.usuarioConectade = usuarioConectade;
    }

    public void setAmbNome(String ambNome) {
        this.ambNome = ambNome;
    }

    /**
     * Creates new form tela
     */
    public chat() {
        initComponents();
        initAssets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atualizarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuariosList = new javax.swing.JList<>();
        textoBoasVindas = new javax.swing.JLabel();
        usuarioConectado = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mensagemArea = new javax.swing.JTextArea();
        enviarButton = new javax.swing.JButton();
        usuarioDestinatario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mensagemTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        atualizarButton.setText("Atualizar");
        atualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButtonActionPerformed(evt);
            }
        });

        usuariosList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuariosListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usuariosList);

        textoBoasVindas.setText(("<html>"+"você está no " + ambNome + ", selecione um usuário"+"<br>"+"para conversar"+"</html>"));

        usuarioConectado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usuarioConectado.setText(usuarioConectade);
        usuarioConectado.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                usuarioConectadoComponentShown(evt);
            }
        });

        mensagemArea.setEditable(false);
        mensagemArea.setBackground(new java.awt.Color(255, 255, 255));
        mensagemArea.setColumns(20);
        mensagemArea.setRows(5);
        jScrollPane3.setViewportView(mensagemArea);

        enviarButton.setText("Enviar");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        usuarioDestinatario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usuarioDestinatario.setText("bate papo com o userN");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("mensagens recebidas");

        mensagemTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensagemTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoBoasVindas, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(atualizarButton))
                        .addComponent(mensagemTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(enviarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(usuarioDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(usuarioConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoBoasVindas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usuarioDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensagemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviarButton)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButtonActionPerformed
         
        String mensagem = tela.controle.receberMensagem(usuarioConectade, ambNome);
        mensagemArea.append(mensagem);

    }//GEN-LAST:event_atualizarButtonActionPerformed


    private void usuariosListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosListMouseClicked
        usuarioDestinatario.setText("bate papo com o " + usuariosList.getSelectedValue());
    }//GEN-LAST:event_usuariosListMouseClicked

    private void usuarioConectadoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_usuarioConectadoComponentShown
    }//GEN-LAST:event_usuarioConectadoComponentShown

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        usuarioConectado.setText(usuarioConectade);
        textoBoasVindas.setText("<html>" + "você está no " + ambNome + ", selecione um usuário" + "<br>" + "para conversar" + "</html>");
    }//GEN-LAST:event_formMouseEntered

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        tela.controle.enviarMensagem(usuariosList.getSelectedValue(), usuarioConectade, ambNome, mensagemTextField.getText());

    }//GEN-LAST:event_enviarButtonActionPerformed

    private void mensagemTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensagemTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mensagemTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new chat().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarButton;
    private javax.swing.JButton enviarButton;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea mensagemArea;
    private javax.swing.JTextField mensagemTextField;
    private javax.swing.JLabel textoBoasVindas;
    private javax.swing.JLabel usuarioConectado;
    private javax.swing.JLabel usuarioDestinatario;
    private javax.swing.JList<String> usuariosList;
    // End of variables declaration//GEN-END:variables
}
