/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ifce;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Action;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author walmi
 */
public class tela extends javax.swing.JFrame {

    ControleTela controle = new ControleTela();
    DefaultListModel ambList = new DefaultListModel();
    DefaultListModel dispList = new DefaultListModel();
    DefaultListModel userList = new DefaultListModel();
    private JButton buttonExcluir;

    //add a lista
    private void addArgumentToList(String argument, DefaultListModel listModel, JList list) {
        list.setModel(listModel);
        listModel.addElement(argument);
    }

    /**
     * Creates new form tela
     */
    public tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ambienteButton = new javax.swing.JButton();
        dispositivoButton = new javax.swing.JButton();
        usuarioButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ambienteList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        dispositivoList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        usuarioList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ambienteButton.setText("Ambiente");
        ambienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambienteButtonActionPerformed(evt);
            }
        });

        dispositivoButton.setText("Dispositivo");
        dispositivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispositivoButtonActionPerformed(evt);
            }
        });

        usuarioButton.setText("Usuário");
        usuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioButtonActionPerformed(evt);
            }
        });

        ambienteList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ambienteListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ambienteList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ambienteListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ambienteList);

        dispositivoList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispositivoListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dispositivoList);

        usuarioList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(usuarioList);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("criar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(ambienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(dispositivoButton)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(usuarioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ambienteButton)
                    .addComponent(usuarioButton)
                    .addComponent(dispositivoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ambienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambienteButtonActionPerformed
        //Cria um novo ambiente
        addArgumentToList(controle.criarAmbiente(), ambList, ambienteList);
    }//GEN-LAST:event_ambienteButtonActionPerformed

    private void dispositivoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispositivoButtonActionPerformed
        //Cria um novo dispositivo
        addArgumentToList(controle.criarDispositivo(), dispList, dispositivoList);
    }//GEN-LAST:event_dispositivoButtonActionPerformed

    private void ambienteListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ambienteListAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ambienteListAncestorAdded

    private void dispositivoListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dispositivoListMouseClicked
        // Crie um JTextField
        JTextField txtAmb = new JTextField("amb");

        // Crie um painel personalizado contendo a mensagem, o JTextField e os botões
        Object[] opcoes = {"Excluir Dispositivo", "Mover Dispositivo", "Cancelar"};
        JPanel panel = new JPanel(new BorderLayout());
        panel.add(new JLabel("Escolha uma opção:"), BorderLayout.NORTH);
        panel.add(txtAmb, BorderLayout.CENTER);

        // Mostre a caixa de diálogo
        int escolha = JOptionPane.showOptionDialog(null, panel, "Informações do " + dispositivoList.getSelectedValue(), JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opcoes, opcoes[0]);

        //Trata a opção que o usuario escolheu
        if (escolha == 0) {
            controle.excluirDispositivo(dispositivoList.getSelectedValue());
            //atualizar a lista
            int index = dispositivoList.getSelectedIndex();
            dispList.removeElementAt(index);
        } else if (escolha == 1) {
            controle.moverDispositivo(dispositivoList.getSelectedValue(), txtAmb.getText());
        } else if (escolha == 2) {

        }

    }//GEN-LAST:event_dispositivoListMouseClicked

    private void ambienteListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ambienteListMouseClicked
        // Crie um painel personalizado contendo a mensagem e os botões
        Object[] opcoes = {"Excluir Ambiente", "Cancelar"};

        // Mostre a caixa de diálogo
        int escolha = JOptionPane.showOptionDialog(null, controle.listarDispositivo(ambienteList.getSelectedValue()) + controle.listarUsuario(ambienteList.getSelectedValue()), "Informações do " + ambienteList.getSelectedValue(), JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opcoes, opcoes[0]);

        //Trata a opção que o usuario escolheu
        if (escolha == 0) {

            if (controle.contadorDispositivos(ambienteList.getSelectedValue()) == 0) {
                controle.excluirAmbiente(ambienteList.getSelectedValue());

                //atualizar a lista
                int index = ambienteList.getSelectedIndex();
                ambList.removeElementAt(index);
            } else {
                //Warning
                JLabel lblMessage = new JLabel("Antes de destruir o ambiente, remova todos os dispositivos e usuários.");
                Object[] texts = {lblMessage};
                JOptionPane.showMessageDialog(null, texts);
            }

        }

    }//GEN-LAST:event_ambienteListMouseClicked

    private void usuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioButtonActionPerformed
        //Cria um novo usuario
        addArgumentToList(controle.criarUsuario(), userList, usuarioList);
    }//GEN-LAST:event_usuarioButtonActionPerformed

    private void usuarioListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioListMouseClicked
        // Crie um JTextField
        JTextField txtAmb1 = new JTextField("amb");

        // Crie um painel personalizado contendo a mensagem, o JTextField e os botões
        Object[] opcoes = {"Excluir Usuário", "Mover Usuário", "Cancelar"};
        JPanel panel = new JPanel(new BorderLayout());
        panel.add(new JLabel("Escolha uma opção:"), BorderLayout.NORTH);
        panel.add(txtAmb1, BorderLayout.CENTER);

        // Mostre a caixa de diálogo
        int escolha = JOptionPane.showOptionDialog(null, panel, "Informações do " + usuarioList.getSelectedValue(), JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opcoes, opcoes[0]);

        //Trata a opção que o usuario escolheu
        if (escolha == 0) {
            controle.excluirDispositivo(dispositivoList.getSelectedValue());
            //atualizar a lista
            int index = usuarioList.getSelectedIndex();
            userList.removeElementAt(index);
        } else if (escolha == 1) {
            controle.moverUsuario(usuarioList.getSelectedValue(), txtAmb1.getText());
        } else if (escolha == 2) {

        }
    }//GEN-LAST:event_usuarioListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ambienteButton;
    private javax.swing.JList<String> ambienteList;
    private javax.swing.JButton dispositivoButton;
    private javax.swing.JList<String> dispositivoList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton usuarioButton;
    private javax.swing.JList<String> usuarioList;
    // End of variables declaration//GEN-END:variables
}
